server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path= /user/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
              - Path= /rating/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
              - Path= /hotels/**


okta:
  oauth2:
    issuer: https://dev-11989600.okta.com/oauth2/default
    audience: api://default
    client-id: 0oafb45bk7YOiKuMP5d7
    client-secret: rQhNVfNG54LAN_8G-GASOeRm4HCGLnOJOOoQy5O9jcxp2X3fW5F1q6g8awbuvNjc
    scopes: openid, profile, email, offline_access




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/